[package]
name = "soundcloud"
authors = [
    "Mikkel Kroman <mk@uplink.io>",
    "Max Jöhnk <maxjoehnk@gmail.com>",
    "Aaron Enberg <aaronenberg@gmail.com>",
    "Herman Gohn <gohnherman@gmail.com>"
]
version = "0.4.0"
license = "MIT/Apache-2.0"
keywords = ["soundcloud", "http", "api", "client"]
repository = "https://github.com/maxjoehnk/soundcloud-rs"
description = "SoundCloud API implementation in Rust"
edition = "2018"
categories = ["api-bindings"]
readme = "README.md"

[badges]
travis-ci = { repository = "maxjoehnk/soundcloud-rs" }
is-it-maintained-issue-resolution = { repository = "https://github.com/maxjoehnk/soundcloud-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/maxjoehnk/soundcloud-rs" }
maintenance = { status = "actively-developed" }

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.1"
futures = "0.3"

[dependencies.reqwest]
version = "^0.12.4"
features = ["json", "stream"]

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { version = "~0.6.0", features = ["compat"] }
